# Generated by Django 4.2.7 on 2025-07-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_day', models.FloatField(default=9.0)),
                ('half_day_min', models.FloatField(default=5.0)),
                ('half_day_max', models.FloatField(default=9.0)),
            ],
        ),
    ]
