# Generated by Django 4.2.7 on 2025-07-29 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerule',
            name='add_extra_full_days',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerule',
            name='only_check_in_out',
            field=models.BooleanField(default=False),
        ),
    ]
