# Generated by Django 4.2.7 on 2025-08-12 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_attendancerule_add_extra_full_days_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSummary',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('total_days', models.PositiveIntegerField()),
                ('weekly_offs', models.PositiveIntegerField()),
                ('working_days', models.PositiveIntegerField()),
                ('full_days', models.PositiveIntegerField()),
                ('half_days', models.PositiveIntegerField()),
                ('absent_days', models.PositiveIntegerField()),
                ('extra_hours', models.FloatField(blank=True, null=True)),
                ('effective_days', models.FloatField()),
                ('leaves_taken', models.FloatField()),
                ('adjusted_leaves', models.FloatField()),
                ('lwp', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=15)),
                ('attendance_summary', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to='app.attendancesummary')),
            ],
        ),
    ]
