# Generated by Django 5.2.5 on 2025-09-04 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_attendancesummary_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesummary',
            name='employee_id',
            field=models.CharField(max_length=25, primary_key=True, serialize=False),
        ),
    ]
