# Generated by Django 5.2.5 on 2025-09-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_attendancesummary_employee_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesummary',
            name='only_check_in',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='only_check_out',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
